name: Dynamic ZIP Extraction

on:
  push:
    branches:
      - main  # atau nama branch utama Anda

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Find and Extract ZIP files
      run: |
        shopt -s nullglob
        zip_files=(*.zip)
        if [ ${#zip_files[@]} -eq 0 ]; then
          echo "No ZIP files found in the repository."
          exit 0
        fi
        for zip_file in "${zip_files[@]}"; do
          echo "Extracting $zip_file"
          unzip -o "$zip_file" -d "${zip_file%.zip}"
          rm "$zip_file"
        done
    
    - name: Commit extracted files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git diff --quiet && git diff --staged --quiet || (git commit -m "Extract ZIP files" -a)
    
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Check for extraction
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          echo "ZIP files were found and extracted."
        else
          echo "No changes were made. Either no ZIP files were found or they were already extracted."
        fi
